In [ ]:
import numpy as np
import pandas as pd


# t-test for ne sample

In [2]:
ages = [10,20,30,40,35,16,78,34,20,35,60,50,75,80,60,50,65,78,90,40,50,67,56,78,34,18,45,47,16,18]

In [3]:
len(ages)

30

In [4]:
np.mean(ages)

46.5

In [5]:
age_sample= np.random.choice(ages,10)

In [6]:
age_sample

array([40, 18, 78, 45, 40, 20, 67, 78, 60, 30])

In [7]:
from scipy.stats import ttest_1samp

In [8]:
t_test,p_values = ttest_1samp(age_sample,46.5)

In [9]:
print(p_values)

0.8791214833546621


In [10]:
print(t_test)

0.15646313356881283


# more examples on one sample

In [11]:
import  scipy.stats as stats 


In [21]:
np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages = stats.poisson.rvs(loc=18,mu=30,size=60)

In [22]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [23]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [25]:
from scipy.stats import ttest_1samp 
_,p_value = ttest_1samp(classA_ages,school_ages.mean())

In [26]:
p_value

1.139027071016194e-13

In [27]:
if p_value<0.05:
    print("we rejest our null hypothesis")
else:
    print("we accept our null hypothesis")

we rejest our null hypothesis


# TWO SAMPLE T-TEST

In [28]:
np.random.seed(12)
classb_ages = stats.poisson.rvs(loc=18,mu=33,size=60)

In [30]:
_,p_value = stats.ttest_ind(classA_ages,classb_ages,equal_var=False)

In [31]:
p_value

0.00039942095100859375

In [32]:
if p_value<0.05:
    print("we rejest our null hypothesis")
else:
    print("we accept our null hypothesis")

we rejest our null hypothesis


# PAIRED SAMPLE T-TEST

In [37]:
weight1 = [25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2 = weight1 + stats.norm.rvs(scale=5,loc=1.25,size=15)

In [40]:
weight =pd.DataFrame({"weight1":np.array(weight1),"weight2":np.array(weight2),
                     "weight_change":np.array(weight1)-np.array(weight2)})

In [41]:
weight

weight1    weight2  weight_change
0        25  18.684564       6.315436
1        30  27.432348       2.567652
2        28  30.496016      -2.496016
3        35  28.300957       6.699043
4        28  24.352370       3.647630
5        34  35.863808      -1.863808
6        26  35.696460      -9.696460
7        29  31.138749      -2.138749
8        30  31.410030      -1.410030
9        26  36.916078     -10.916078
10       28  23.939526       4.060474
11       32  29.586855       2.413145
12       31  36.463707      -5.463707
13       30  36.633700      -6.633700
14       45  48.538453      -3.538453

In [42]:
_,p_value = stats.ttest_rel(weight1,weight2)

In [43]:
p_value

0.39907052675466614

In [44]:
if p_value<0.05:
    print("we rejest our null hypothesis")
else:
    print("we accept our null hypothesis")

we accept our null hypothesis
